### ISSUE TITLE
Tensor not have the equal size while training the diffuse model

### ISSUE THREAD

**Issue by wangfusehng** [RobinWitch/SynTalker#5]
![QQ20241117-131330](https://github.com/user-attachments/assets/95be588b-acb1-456f-9367-acf932a47023)
![QQ20241117-131453](https://github.com/user-attachments/assets/74352223-df64-40c9-9c6d-d259adb34711)

![QQ20241117-131616](https://github.com/user-attachments/assets/839c2c4f-a3f0-42bb-a560-38d37ed46745)
The first three training steps have been excuted successfully and I have redownloaded the dataset but it still shows this problem.

**Comment by RobinWitch** [comment]
It is so strange...I can't reproduce it, even trying on other three different machines. According to your log images, it seems that the first training batch step run correctly but error in the next step.
I suggest you can set 'batch_size' to 1 for debugging to find which item cause this 'tensor shape' error.

**Comment by wangfusehng** [comment]
When i set the batch_size=1 and print the shape of text_feat,i found the problem see the pecture below,it could be the problem of dataset or this code
 self.text_pre_encoder_body = nn.Embedding.from_pretrained(torch.FloatTensor(pre_trained_embedding),freeze=args.t_fix_pre)
text_feat = self.text_pre_encoder_body(y['word'])
and when i change the batch_size the shape problem appears again

![75b6a9a6-a48a-4775-94fc-71f71815f9bc](https://github.com/user-attachments/assets/836e7d25-49f6-4faf-b9c2-c4d54849d607)


![ca5fefbb-1975-4ff4-bd4e-99d6344aabcc](https://github.com/user-attachments/assets/71c99aee-dabe-4e50-83ef-dd6293a34323)
![image](https://github.com/user-attachments/assets/aea8d8dd-8c58-41c7-a07a-988716978bd5)
![image](https://github.com/user-attachments/assets/eb7ca0b5-2b0e-4f71-80cc-0bd824fe7440)

**Comment by RobinWitch** [comment]
According to your log, it seems like there is a special item y['word'] have a different shape [128,2] instead of [128].
You can set `new_cache` to `True` in config file, delete all cache file in dir `datasets/BEAT_SMPL/beat_v2.0.0/beat_english_v2.0.0/fasttext`, run the code and add a check or assertion to ensure in https://github.com/RobinWitch/SynTalker/blob/6d0a67794040679eba06df9cabfad9ed7f4aa9be/dataloaders/beat_sep_lower.py#L536

https://github.com/RobinWitch/SynTalker/blob/6d0a67794040679eba06df9cabfad9ed7f4aa9be/dataloaders/beat_sep_lower.py#L714

https://github.com/RobinWitch/SynTalker/blob/6d0a67794040679eba06df9cabfad9ed7f4aa9be/dataloaders/beat_sep_lower.py#L768

 that above relevant varient dimension  is correct or not.

**Comment by wangfusehng** [comment]
After doing what you have said above, the model was trained successfully! The problem is mostly resulted by the cache.
Great work, hope for your next research about co-speech gesture Synthesis.
![image](https://github.com/user-attachments/assets/64ab4a6f-b5e6-4d0c-bccf-67f0f2597d6e)
